### ISSUE TITLE
What are best practices?

### ISSUE THREAD

**Issue by jaunt** [mtraver/gaelog#2]
Hello, thanks for putting this together.  If you have time to answer this I'd greatly appreciate it:

Is the idea to create the logger client and destroy it on every request?  What about in the case of using chained middleware (I'm using echo labstack but they're all similar I think).  It would seem crazy to create and destroy on every log call, but then how do I easily make sure it gets created/destroyed a the beginning/end of the chain of handlers I have?  

Is this still the best way forward given app engine standard is on 1.13?  Is there any other alternatives?  Seems like logging is a massive weak spot with app engine standard right now. 

Thanks again for this project.

**Comment by mtraver** [comment]
Hello! I've only used it by creating and destroying on each request, but you make a great point about middleware. One option is to attach the logger to the context so you can pass it through the chain. A colleague made a similar package that works like that: https://github.com/broady/aelog. Check his out, and/or I could add such functionality to this package.

Go 1.11 on GAE supports the App Engine APIs but all versions after 1.11 do not, so there's no difference w.r.t. logging in 1.13. There is another way to do it, but the essence is the same. If you write a JSON-encoded payload containing certain fields to files under `/var/log` [1] the logs will be passed along to Stackdriver and correlated. This package does that: https://github.com/a1comms/go-gaelog. The documentation about that is [here](https://cloud.google.com/appengine/docs/standard/go/writing-application-logs) but it's rather sparse.


[1] I think `stdout` works too, but `/var/log` allows you to categorize logs for easier filtering in Stackdriver.

**Comment by mtraver** [comment]
I added handler wrapping functionality and released it in v0.2.0. The example is updated too.

**Comment by jaunt** [comment]
Nice, thanks for the explanation!

**Comment by jaunt** [comment]
Note, I've also been experimenting with this solution using logrus.  https://github.com/andyfusniak/stackdriver-gae-logrus-plugin

**Comment by mtraver** [comment]
That's neat! Looks like a nice solution.
